#! /bin/bash
#
# (C) Copyright IBM Corporation 2016.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# inform the user how to use the image
cat <<EOF
This is an S2I WebSphere-Liberty 8.5.5.8 base image that is responsible for consuming a JEE project and deploying it onto a WebSphere-Liberty Application server.
To Use it, install S2I at: https://github.com/openshift/source-to-image.

Sample invocation:

s2i build https://github.com/jamiecoleman92/sample.ferret.git jamielcoleman/liberty:v5 libertys2itest

You can then run the resulting image via
docker run -p libertys2itest

Details:
If a pom.xml file is present in the source directory then the project is built with maven and the output in target will be copied into the Liberty deployments directory /opt/ibm/wlp/usr/servers/defaultServer/dropins/.
The WebSphere-Liberty start script located in /opt/ibm/wlp/bin/ is called when the container is run which in turn checks to see if an application is present in the /dropins folder then runs it.
EOF
